"""Add demo_progress table

Revision ID: b7e5c70a2d97
Revises: 0001_existing_schema
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'b7e5c70a2d97'
down_revision: str | Sequence[str] | None = '0001_existing_schema'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('draft_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], name='demo_progress_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='app'
    )
    # ### end Alembic commands ###
    op.execute("ALTER TABLE app.demo_progress ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo_progress', schema='app')
    # ### end Alembic commands ###
